version: '3.4'

services:
  # postmortem.web:
  #   image: ${DOCKER_REGISTRY-}postmortemweb
  #   build:
  #     context: .
  #     dockerfile: PostMortem.Web/Dockerfile
  #   ports:
  #     - 6777:80
  #   links:f#     - mongodb
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:latest
    build:
      context: .
    container_name: "mongodb_postmortem"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 29017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet